services:
  frontend:
    build: ./frontend
    container_name: blog-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: blog-backend
    ports:
      - '8000:8000'
    environment:
      MONGO_URL: mongodb://mongo:27017
      DATABASE_NAME: blogapp
    volumes:
      - ./backend:/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: blog-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
