apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: blog-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: bloguser
  MONGO_INITDB_ROOT_PASSWORD: blogpassword
  MONGO_REPLICA_SET_KEY: BloggyReplicaSetKey1234567890
